### ISSUE TITLE
Fix typo in National standard in StructuralLoadCombination

### ISSUE THREAD

**Issue by msalak-scia** [StructuralAnalysisFormat/StructuralAnalysisFormat-Doc#155]
First two values in the
object: StructuralLoadCombination
Column header: National Standard
enum definition:

**EN-ULS(STR/GEO) Set B
EN-ULS (STR/GEO) Set C**
EN-Accidental 1
EN-Accidental 2
...

The first value there is no space: EN-ULS(STR/GEO)...
The second value has a space inside: EN-ULS (STR/GEO)...

Unify those values, by adding the space in the first value.

**Comment by msalak-scia** [comment]
I am a little puzzled how that would affect backward compatibility, could you please help @dschuermans? Does this mean I can no longer open older versions, therefore new version would have to be 3.0.0?

**Comment by dschuermans** [comment]
@msalak-scia shouldn't affect it. 
This is just a matter of providing alternative translations for those values that you want to fix, which we've already done in the past
That way, both old & new values will work.

But now that I look at it, https://github.com/StructuralAnalysisFormat/StructuralAnalysisFormat-SDK/issues/96 seems to have already fixed this in the SDK.
Weren't the docs updated?
