### ISSUE TITLE
Update required value for Location in StructuralCurveAction and StructuralCurveMoment

### ISSUE THREAD

**Issue by msalak-scia** [StructuralAnalysisFormat/StructuralAnalysisFormat-Doc#62]
There is a contradiction in pages StructuralCurveAction and StructuralCurveMoment. Required value for 'Location' is 'yes' but it should be 'yes if coordinate system = Global' as it is described in the description below the table.

**Comment by dschuermans** [comment]
In the SDK, instead of validating it as a required property, we set a default value of "Length" if the property is NULL.
Is this still OK?

**Comment by msalak-scia** [comment]
The current solution works, but it is not clean and precise.  I would suggest making it precise:

Required value for Location: YES IF Coordinate system = Global

I would also not export anything (in SDK) if Coordinate system = Local and validate it as a required property if the condition is met, to keep it consistent.

Easier option would be just to change the note under table to be more clear and leave everything as it is. What do you think? @sonkaste17 @dschuermans

**Comment by msalak-scia** [comment]
We will use the simplest fix:

- [ ] Leave required value of Location to yes
- [ ] Update description with all the possible option:
    > Aplicable options are:
    > * for Coordinate system = local: Lenght
    > * for Coordinate system global: Length, Projection
- [ ] Update note below the table by deleting the line that states 'location is used only for global coordnate system'

Leave SDK as it is.
