### ISSUE TITLE
Provide a description for constraints of support objects (explain tension-only, compression-only relation to GCS, LCS)

### ISSUE THREAD

**Issue by sonkaste17** [StructuralAnalysisFormat/StructuralAnalysisFormat-Doc#92]
In SAF we have "supports" objects (StructuralPointSupport ... ) with predefined constraints. These constraints have multiple possible values. Now, we are not explaining enough difference between tension-only and compression-only (flexible tension only / flexible compression only). This behaviour is related to position of support that is not described in the documentation. Currently, the compression acts always in opposite direction to the positive GCS axis - Please add that information to all relevant support objects. See the picture below.

![image](https://user-images.githubusercontent.com/81751485/151180967-5e83439d-cbeb-46ac-8b96-cbaaa3aebf99.png)

**Comment by msalak-scia** [comment]
internal number 5524
