### ISSUE TITLE
Please add explanation for support type objects to LCS and GCS - with pictures

### ISSUE THREAD

**Issue by sonkaste17** [StructuralAnalysisFormat/StructuralAnalysisFormat-Doc#99]
For StrucutralPointSupport LCS does not make sense.
For Supports applicable on edges, the edge LCS is taken into account but it is not described.
For Supports applicable on 1D members - LCS is related to the LCS of the member. Is it mentioned in spec?

Thank you for the investigation, similar needs to be done for loads.

**Comment by msalak-scia** [comment]
internal reference number 5585
